// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void googleClassRoomWithoutLogin() {
    driver.get("https://classroom.google.com/signin/v2/sl/pwd?service=classroom&passive=1209600&continue=https%3A%2F%2Fclassroom.google.com%2F&followup=https%3A%2F%2Fclassroom.google.com%2F&emr=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin");
    driver.manage().window().setSize(new Dimension(550, 691));
    driver.findElement(By.name("password")).sendKeys(""vekmcbZ84!");
    driver.findElement(By.cssSelector("#passwordNext .RveJvd")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".gb_Ea"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".gHz6xd:nth-child(8) .onkcGd > .YVvGBb:nth-child(1)")).click();
    js.executeScript("window.scrollTo(0,0)");
    {
      WebElement element = driver.findElement(By.linkText("Задания"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Задания")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".gb_ve")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".gb_xa"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.close();
    driver.close();
  }
  @Test
  public void googleClassRoom() {
    driver.get("https://classroom.google.com/h");
    driver.manage().window().setSize(new Dimension(550, 691));
    {
      WebElement element = driver.findElement(By.cssSelector(".gb_Ea"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".gb_Ea"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".gHz6xd:nth-child(8) .onkcGd > .YVvGBb:nth-child(1)")).click();
    js.executeScript("window.scrollTo(0,0)");
    {
      WebElement element = driver.findElement(By.id("UGb2Qe"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.close();
  }
}
